from typing import Dict, List
from app.models import Node, NodeType, FinancingInstrument, AssetState

# Deterministic UUIDs for consistency across sessions
APPAREL_IDS = {
    "cotton": "a1111111-1111-4111-8111-111111111111",
    "weaving": "a2222222-2222-4222-8222-222222222222",
    "garment": "a3333333-3333-4333-8333-333333333333",
    "ocean": "a4444444-4444-4444-8444-444444444444",
    "customs": "a5555555-5555-4555-8555-555555555555",
    "warehouse": "a6666666-6666-4666-8666-666666666666",
    "delivery": "a7777777-7777-4777-8777-777777777777",
}

ELECTRONICS_IDS = {
    "wafer": "e1111111-1111-4111-8111-111111111111",
    "pcb": "e2222222-2222-4222-8222-222222222222",
    "smt": "e3333333-3333-4333-8333-333333333333",
    "air_freight": "e4444444-4444-4444-8444-444444444444",
    "cross_dock": "e5555555-5555-4555-8555-555555555555",
    "tech_hub": "e6666666-6666-4666-8666-666666666666",
    "enterprise": "e7777777-7777-4777-8777-777777777777",
}

TEMPLATES: Dict[str, Dict] = {
    "apparel": {
        "id": "apparel",
        "name": "Fast-Fashion Apparel Supply Chain",
        "description": "High-velocity global garment supply chain from organic cotton farm to international retail distribution.",
        "nodes": [
            Node(
                id=APPAREL_IDS["cotton"],
                name="Organic Cotton Farms",
                type=NodeType.FACTORY,
                cost=140000.0,
                baseCost=140000.0,
                delayDays=0.0,
                baseLeadTimeDays=10.0,
                dependsOn=[],
                financingInstrument=FinancingInstrument.PO_FINANCING,
                assetState=AssetState.UNFINANCED,
                loanAmount=119000.0,
                ltvRatio=0.85,
                riskScore=0.08,
                interestRate=6.80,
                tier=1,
                supplierReliabilityScore=0.96,
                batchId="BATCH-NX-2026-A1",
                position={"x": 60, "y": 140}
            ),
            Node(
                id=APPAREL_IDS["weaving"],
                name="Spinning & Weaving Mill",
                type=NodeType.FACTORY,
                cost=220000.0,
                baseCost=220000.0,
                delayDays=0.0,
                baseLeadTimeDays=12.0,
                dependsOn=[APPAREL_IDS["cotton"]],
                financingInstrument=FinancingInstrument.PO_FINANCING,
                assetState=AssetState.UNFINANCED,
                loanAmount=187000.0,
                ltvRatio=0.85,
                riskScore=0.10,
                interestRate=7.10,
                tier=1,
                supplierReliabilityScore=0.92,
                batchId="BATCH-NX-2026-A1",
                position={"x": 300, "y": 140}
            ),
            Node(
                id=APPAREL_IDS["garment"],
                name="Garment Assembly Plant",
                type=NodeType.FACTORY,
                cost=350000.0,
                baseCost=350000.0,
                delayDays=0.0,
                baseLeadTimeDays=14.0,
                dependsOn=[APPAREL_IDS["weaving"]],
                financingInstrument=FinancingInstrument.PO_FINANCING,
                assetState=AssetState.UNFINANCED,
                loanAmount=297500.0,
                ltvRatio=0.85,
                riskScore=0.12,
                interestRate=7.30,
                tier=1,
                supplierReliabilityScore=0.90,
                batchId="BATCH-NX-2026-A1",
                position={"x": 540, "y": 140}
            ),
            Node(
                id=APPAREL_IDS["ocean"],
                name="Ocean Cargo Route 4 (Red Sea / Suez)",
                type=NodeType.TRANSIT,
                cost=195000.0,
                baseCost=195000.0,
                delayDays=0.0,
                baseLeadTimeDays=18.0,
                dependsOn=[APPAREL_IDS["garment"]],
                financingInstrument=FinancingInstrument.ASSET_BACKED_LENDING,
                assetState=AssetState.UNFINANCED,
                loanAmount=156000.0,
                ltvRatio=0.80,
                riskScore=0.14,
                interestRate=7.80,
                tier=2,
                batchId="BATCH-NX-2026-A1",
                position={"x": 780, "y": 140}
            ),
            Node(
                id=APPAREL_IDS["customs"],
                name="Deep-Sea Port & Customs Gateway",
                type=NodeType.TRANSIT,
                cost=85000.0,
                baseCost=85000.0,
                delayDays=0.0,
                baseLeadTimeDays=4.0,
                dependsOn=[APPAREL_IDS["ocean"]],
                financingInstrument=FinancingInstrument.ASSET_BACKED_LENDING,
                assetState=AssetState.UNFINANCED,
                loanAmount=68000.0,
                ltvRatio=0.80,
                riskScore=0.15,
                interestRate=8.00,
                tier=2,
                batchId="BATCH-NX-2026-A1",
                position={"x": 1020, "y": 140}
            ),
            Node(
                id=APPAREL_IDS["warehouse"],
                name="Central Fulfilment Center",
                type=NodeType.WAREHOUSE,
                cost=160000.0,
                baseCost=160000.0,
                delayDays=0.0,
                baseLeadTimeDays=6.0,
                dependsOn=[APPAREL_IDS["customs"]],
                financingInstrument=FinancingInstrument.INVENTORY_FINANCING,
                assetState=AssetState.UNFINANCED,
                loanAmount=120000.0,
                ltvRatio=0.75,
                riskScore=0.12,
                interestRate=7.60,
                tier=3,
                storageDurationDays=8.0,
                batchId="BATCH-NX-2026-A1",
                position={"x": 1260, "y": 140}
            ),
            Node(
                id=APPAREL_IDS["delivery"],
                name="Global Retail Network & Invoicing",
                type=NodeType.DELIVERY,
                cost=280000.0,
                baseCost=280000.0,
                delayDays=0.0,
                baseLeadTimeDays=3.0,
                dependsOn=[APPAREL_IDS["warehouse"]],
                financingInstrument=FinancingInstrument.INVOICE_FACTORING,
                assetState=AssetState.UNFINANCED,
                loanAmount=274400.0,
                ltvRatio=0.98,
                riskScore=0.08,
                interestRate=2.00,
                tier=4,
                batchId="BATCH-NX-2026-A1",
                position={"x": 1500, "y": 140}
            )
        ]
    },
    "electronics": {
        "id": "electronics",
        "name": "Electronics & Semiconductor Chain",
        "description": "Multi-tier tech manufacturing chain from silicon foundries to global OEM enterprise delivery.",
        "nodes": [
            Node(
                id=ELECTRONICS_IDS["wafer"],
                name="Silicon Wafer Foundry",
                type=NodeType.FACTORY,
                cost=340000.0,
                baseCost=340000.0,
                delayDays=0.0,
                baseLeadTimeDays=16.0,
                dependsOn=[],
                financingInstrument=FinancingInstrument.PO_FINANCING,
                assetState=AssetState.UNFINANCED,
                loanAmount=289000.0,
                ltvRatio=0.85,
                riskScore=0.07,
                interestRate=6.60,
                tier=1,
                supplierReliabilityScore=0.97,
                batchId="BATCH-NX-2026-E2",
                position={"x": 60, "y": 140}
            ),
            Node(
                id=ELECTRONICS_IDS["pcb"],
                name="PCB & Substrate Fabricator",
                type=NodeType.FACTORY,
                cost=210000.0,
                baseCost=210000.0,
                delayDays=0.0,
                baseLeadTimeDays=10.0,
                dependsOn=[ELECTRONICS_IDS["wafer"]],
                financingInstrument=FinancingInstrument.PO_FINANCING,
                assetState=AssetState.UNFINANCED,
                loanAmount=178500.0,
                ltvRatio=0.85,
                riskScore=0.09,
                interestRate=7.00,
                tier=1,
                supplierReliabilityScore=0.94,
                batchId="BATCH-NX-2026-E2",
                position={"x": 300, "y": 140}
            ),
            Node(
                id=ELECTRONICS_IDS["smt"],
                name="Mainboard SMT & Assembly",
                type=NodeType.FACTORY,
                cost=460000.0,
                baseCost=460000.0,
                delayDays=0.0,
                baseLeadTimeDays=12.0,
                dependsOn=[ELECTRONICS_IDS["pcb"]],
                financingInstrument=FinancingInstrument.PO_FINANCING,
                assetState=AssetState.UNFINANCED,
                loanAmount=391000.0,
                ltvRatio=0.85,
                riskScore=0.11,
                interestRate=7.20,
                tier=1,
                supplierReliabilityScore=0.91,
                batchId="BATCH-NX-2026-E2",
                position={"x": 540, "y": 140}
            ),
            Node(
                id=ELECTRONICS_IDS["air_freight"],
                name="Transpacific Express Air Cargo",
                type=NodeType.TRANSIT,
                cost=280000.0,
                baseCost=280000.0,
                delayDays=0.0,
                baseLeadTimeDays=4.0,
                dependsOn=[ELECTRONICS_IDS["smt"]],
                financingInstrument=FinancingInstrument.ASSET_BACKED_LENDING,
                assetState=AssetState.UNFINANCED,
                loanAmount=229600.0,
                ltvRatio=0.82,
                riskScore=0.10,
                interestRate=7.40,
                tier=2,
                batchId="BATCH-NX-2026-E2",
                position={"x": 780, "y": 140}
            ),
            Node(
                id=ELECTRONICS_IDS["cross_dock"],
                name="Airport Customs & Bonded Transit",
                type=NodeType.TRANSIT,
                cost=110000.0,
                baseCost=110000.0,
                delayDays=0.0,
                baseLeadTimeDays=2.0,
                dependsOn=[ELECTRONICS_IDS["air_freight"]],
                financingInstrument=FinancingInstrument.ASSET_BACKED_LENDING,
                assetState=AssetState.UNFINANCED,
                loanAmount=90200.0,
                ltvRatio=0.82,
                riskScore=0.12,
                interestRate=7.70,
                tier=2,
                batchId="BATCH-NX-2026-E2",
                position={"x": 1020, "y": 140}
            ),
            Node(
                id=ELECTRONICS_IDS["tech_hub"],
                name="High-Tech Cleanroom Warehouse",
                type=NodeType.WAREHOUSE,
                cost=220000.0,
                baseCost=220000.0,
                delayDays=0.0,
                baseLeadTimeDays=5.0,
                dependsOn=[ELECTRONICS_IDS["cross_dock"]],
                financingInstrument=FinancingInstrument.INVENTORY_FINANCING,
                assetState=AssetState.UNFINANCED,
                loanAmount=165000.0,
                ltvRatio=0.75,
                riskScore=0.13,
                interestRate=7.50,
                tier=3,
                storageDurationDays=5.0,
                batchId="BATCH-NX-2026-E2",
                position={"x": 1260, "y": 140}
            ),
            Node(
                id=ELECTRONICS_IDS["enterprise"],
                name="OEM Enterprise Invoicing & Handover",
                type=NodeType.DELIVERY,
                cost=520000.0,
                baseCost=520000.0,
                delayDays=0.0,
                baseLeadTimeDays=2.0,
                dependsOn=[ELECTRONICS_IDS["tech_hub"]],
                financingInstrument=FinancingInstrument.INVOICE_FACTORING,
                assetState=AssetState.UNFINANCED,
                loanAmount=509600.0,
                ltvRatio=0.98,
                riskScore=0.06,
                interestRate=2.00,
                tier=4,
                batchId="BATCH-NX-2026-E2",
                position={"x": 1500, "y": 140}
            )
        ]
    }
}

def get_template(template_id: str) -> Dict:
    tid = (template_id or "apparel").lower()
    if tid not in TEMPLATES:
        return TEMPLATES["apparel"]
    # Return deep clone of nodes to avoid mutating global template in-memory
    template = TEMPLATES[tid]
    cloned_nodes = [n.model_copy(deep=True) for n in template["nodes"]]
    return {
        "id": template["id"],
        "name": template["name"],
        "description": template["description"],
        "nodes": cloned_nodes
    }
